### ISSUE TITLE
WebUX: check why the Nakade will miss the killer stone

### ISSUE THREAD

**Issue by madallion** [MicrosoftGeekHub/AlphaGo#11]

**Comment by madallion** [comment]
![image](https://cloud.githubusercontent.com/assets/10472511/14599685/55bf4488-058b-11e6-8cb0-f24dcae87bf3.png)

**Comment by littleq0903** [comment]
https://github.com/MicrosoftGeekHub/AlphaGo/commit/8ec0072a7113e280abd9b7117b8878079e774cd8 should fix this.

Please report if there's any reproduction no matter success or fail.
